# .github/workflows/build_release.yml
name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name "BackOfficeLauncher" --icon="icon.ico" main.py

      - name: Upload Build Artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: built-exe-${{ github.ref_name }}
          path: dist/BackOfficeLauncher.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/BackOfficeLauncher.exe
          name: Release ${{ github.ref_name }}
          body: |
            Автоматический релиз версии ${{ github.ref_name }}
            Собран на GitHub Actions.

            Файл: BackOfficeLauncher.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}